### ISSUE TITLE
GLPI 10 - Network Discovery & SNMP Discovery issue

### ISSUE THREAD

**Issue by ingu1552** [glpi-project/glpi-inventory-plugin#100]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.0-rc3

### Bug description

As guided, for Network discovery & SNMP Network Discovery, I installed "GLPI Inventory Plugin" - rc7 version (latest) on GLPI 10 
Also, as guided I configured and followed all in GLPI inventory for NW discovery. 

Here is the problem that I have: 
In "Discovery status", I can see that It discovered something after the scan and also showed me "Total Discovery Devices" 

but the problem is that NW devices discovered by the scan are NOT imported to GLPI 10. In "Discovery status", it showed that the device imported is none (I re-checked all rules in "Rules for import and link equipments")

Are there any bugs not importing any devices after either SNMP NW discovery or NW discovery scan?
Could you please advise in order to resolve the issue I am facing to?

Thank you in advance.

**Comment by g-bougard** [comment]
Hi @ingu1552 

your XML inventory shows the agent only got a ping from the remote ip.

There's no rule applied, and so displayed, as GLPI didn't applied any rule for such empty inventory. So no, the problem is not from your ruleset.

You must double-check:
 * your snmp credentials are correct
 * your snmp credentials are associated with the ip range
 * the device behind each ip can answer via snmp

You can also check the agent log, eventually enabling debug mode and run again the task.

**Comment by orthagh** [comment]
When testing a scenario similar, i got the rule "Computer constraint (name)" mentionned in the refused equipment log.
If you haven't added any specific rules in your setup, i suggest to reset them, you'll find a button below the rules list.
I suspect your inventory match none of rules (even one to refuse) and fail to import without referencing so.

If you can't reset, here is the last rule you should have in the list and you must create if missing
![image](https://user-images.githubusercontent.com/418844/164643318-33abe1a6-0730-4062-9978-153e8b3c352a.png)

**Comment by trasher** [comment]
Seems a rule issue, not a bug, I close.
