### ISSUE TITLE
1.0.3 - problem with task actors and logs

### ISSUE THREAD

**Issue by WebGregGit** [glpi-project/glpi-inventory-plugin#166]
Today I updated GLPI from 10.0.1 to 10.0.2 and Inventory plugin from 1.0.2 to 1.0.3

Tasks work but...

1. I have two agents with discovery and inventory modules

![image](https://user-images.githubusercontent.com/68922721/176242529-ae61e537-21a0-4d13-8e4d-0c885a1bcc61.png)

Until now, it was so that, for example, selecting the discovery job and adding an actor - I only saw these two agents. Now I can see them all.

![image](https://user-images.githubusercontent.com/68922721/176242950-672fb95d-0b25-431f-846b-1b118a5de40f.png)

2nd problem - no info about job execution:

![image](https://user-images.githubusercontent.com/68922721/176243148-8f203ef9-1f96-414d-94a3-c2fd2dbfc027.png)

But jobs working (edit: not all^1):

![image](https://user-images.githubusercontent.com/68922721/176243366-064a9712-d566-4ab4-8b0e-ffaf1ad55875.png)

^1 Discovery job looks OK. But SNMP is not prepared. The Network inventory status it only shows 1 task that I had before the update. After the update, I added more - and it doesn't get prepared (target and actor - added).

![image](https://user-images.githubusercontent.com/68922721/176248951-313b8084-d724-4908-b52b-959577819632.png)

And BTW... do these fields have to be so narrow?

![image](https://user-images.githubusercontent.com/68922721/176243686-e644834e-283d-46b5-9167-73e94ec30619.png)

I will be offline a few days from tomorrow, so if you need feedback, please be patient until July 6th

**Comment by stonebuzz** [comment]
First issue : 

Can you run this SQL query and pas here result : 

```sql
SELECT agents.`id` as agents_id, agents.`items_id` 
FROM `glpi_agents` as agents 
LEFT JOIN `glpi_computers` as computers ON computers.id = agents.items_id AND agents.itemtype = 'Computer' 
LEFT JOIN `glpi_plugin_glpiinventory_agentmodules` as modules ON modules.`exceptions` LIKE CONCAT('%"', agents.`id`, '"%') OR modules.`is_active` = 1 
WHERE UPPER(modules.`modulename`) = 'NETWORKDISCOVERY' 
AND computers.is_deleted = 0 AND computers.is_template = 0 GROUP BY agents.`id`, agents.`items_id`;
```

Second issue : 

I don't reproduce
Do you have PHP or SQL errors in /var/www/glpi/fiels/_log

Third issue : 

Can you test this PR -> https://github.com/glpi-project/glpi-inventory-plugin/pull/167

Best regards

**Comment by stonebuzz** [comment]
@WebGregGit 

for empty job log, we found an issue from GLPI

Can you try this -> https://github.com/glpi-project/glpi/pull/12050

Best regards

**Comment by redddcyclone** [comment]
This problem affects me too. Before the update, I had some devices added to the SNMP inventory task and the inventory was working fine (even after updating to 1.0.3). Today, I had to delete all the devices to rediscover them. Discovery works fine, and the devices are imported, but after targeting the IP ranges for SNMP inventory, no devices are added to the task, so the inventory does not happen. Tried deleting the task and everything, but the devices don't show up on the task. Only if I add them one by one instead of adding the entire IP range.

**Comment by stonebuzz** [comment]
Hi @redddcyclone 
for SNMP Inventory issue i think is solved by -> https://github.com/glpi-project/glpi/pull/12050

During the Network Discovery, ```itemtype``` attached to agent become "NetworkEquipement" instead of "Computer" (original value must  be keep and it is not)

So when glpi-inventory try to prepare ```SNMP Inventory``` an SQL query for get agent data have a ```WHERE``` clause on ```itemtype = 'Computer'``` (which not match the current ```itemtype``` -> NetworkEquipement)

Can you try with this PR  https://github.com/glpi-project/glpi/pull/12050 ?

Best regards

**Comment by redddcyclone** [comment]
Hi @stonebuzz 

Tried the PR and nothing. Devices don't show up on the task. Also tried deleting the agent and computer that processes the discovery and inventory tasks, and deleted and re-created the tasks as well. Nothing happens. The devices only show up on the inventory task when I add them manually instead of adding IP ranges.

Also, I don't know if it's related, but when the inventory was working (before I deleted the devices), some devices randomly appeared as network equipments (items such as printers and computers were being imported to the network devices section).

**Comment by WebGregGit** [comment]
Hi @stonebuzz 

Ad 1  (SELECT agents.`id` as agents_id, agents.`items_id`...)

MySQL returned an empty result (zero lines)

And the 2nd select:
<html><body>


  | Edytuj | Kopiuj | Usuń | 1 | WAKEONLAN | 0 | ["6","7"]
-- | -- | -- | -- | -- | -- | -- | --
  | Edytuj | Kopiuj | Usuń | 2 | INVENTORY | 1 | []
  | Edytuj | Kopiuj | Usuń | 3 | InventoryComputerESX | 0 | []
  | Edytuj | Kopiuj | Usuń | 4 | NETWORKINVENTORY | 0 | ["7","6"]
  | Edytuj | Kopiuj | Usuń | 5 | NETWORKDISCOVERY | 0 | ["6","7"]
  | Edytuj | Kopiuj | Usuń | 6 | DEPLOY | 1 | []
  | Edytuj | Kopiuj | Usuń | 7 | Collect | 1 | []


</body>
</html>

Ad 2 - nothing in debug mode, nothing in the logs either. 

I installed https://nightly.glpi-project.org/glpi/10.0-1e538be.tar.gz but that didn't change anything.

Maybe I'll try to remove the plugin and install it cleanly.

Ad 3 - much better with https://github.com/glpi-project/glpi-inventory-plugin/pull/167

**Comment by stonebuzz** [comment]
Hi @WebGregGit 
thanks for feedback

Can you check : 
- that your two agents have column  ```itemtype```  set to 'Computer' in the database
- related computers are not deleted

Best regards

**Comment by stonebuzz** [comment]
@WebGregGit 

GLPI Nightly build have an issue with inventory,

can you retry by reverting this -> https://github.com/glpi-project/glpi/commit/1e538bedf9591739a8779e6a7d2ce12b6925799b#diff-8a88e828dd1b1196a241d524583ce59f010c5445ff24da9b67118b920c0f71f3R155

![image](https://user-images.githubusercontent.com/7335054/177118059-468b6f18-000e-43d7-91a4-e0433e4ecd61.png)

**Comment by stonebuzz** [comment]
@WebGregGit , @redddcyclone 

can you confirm that your asset created from NetDiscovery have no IP attached ?

Best regards

**Comment by stonebuzz** [comment]
Hi guys !

I just made some Pull Request that should solve the problems

You need latest GLPI nightly build : [https://nightly.glpi-project.org/glpi/10.0-1e538be.tar.gz](https://nightly.glpi-project.org/glpi/10.0-1e538be.tar.gz)

From this build you need to : 
- Revert this commit -> https://github.com/glpi-project/glpi/commit/1e538bedf9591739a8779e6a7d2ce12b6925799b#diff-8a88e828dd1b1196a241d524583ce59f010c5445ff24da9b67118b920c0f71f3R155
- Add this commit -> https://github.com/glpi-project/glpi/pull/12132

For ```glpiinventory``` you need this -> https://github.com/glpi-project/glpi-inventory-plugin/pull/173

To test you need to : 
- Delete all asset only created from ```netDiscovery``` (because IP are not created)
- Re-run ```netDiscovery``` then ```netInventory```

Best regards

**Comment by WebGregGit** [comment]
@stonebuzz before your reply I also upgraded the agent from 1.2 to 1.4 and got error 400. I don't know if it could have anything to do (https://forum.glpi-project.org/viewtopic.php?id=284242).

1. GLPI nightly build - done. I installed in the morning.
2. Revert this commit - done for src/Agent/Communication/AbstractRequest.php (I didn't find the tests folder, so I didn't touch these files)
3. Added https://github.com/glpi-project/glpi/pull/12132
4. Added https://github.com/glpi-project/glpi-inventory-plugin/pull/173


I haven't done this yet:
- Delete all asset only created from netDiscovery (because IP are not created)
- Re-run netDiscovery then netInventory

But looks better. The actor list does not display all agents. Also jobs:
![image](https://user-images.githubusercontent.com/68922721/177139926-03fbbe5b-00c7-4741-8d91-2ae340dc3271.png)

**Comment by stonebuzz** [comment]
@WebGregGit 


"Re-run netDiscovery then netInventory
Because I don't quite understand what the first step is about. Can I have duplicate devices - one with IP and the other without? Or should I delete everything even if it looks fine? It is rather impossible for me."

Because, with latest version of GLPI, when an asset (Printer or Network Equipement) is added by discovery, IPs are not.
However, the GlpiInventory plugin needs it for the SNMP inventory part from an IP range

You can delete all asset without IPs 

"After the changes, I updated the agent to 1.4 again and this time it connects flawlessly. Most likely there was a connection between this errors."

Is due to this -> https://github.com/glpi-project/glpi/commit/1e538bedf9591739a8779e6a7d2ce12b6925799b#diff-8a88e828dd1b1196a241d524583ce59f010c5445ff24da9b67118b920c0f71f3R155

Agent 1.3 or 1.4 works correctly without this commit.

Best regards

**Comment by WebGregGit** [comment]
@stonebuzz I didn't know why I should delete all assets. Now it is more understandable - if I have an IP I don't have to :) 

Thanks again for your time and help :)

**Comment by redddcyclone** [comment]
Hi @stonebuzz, the pull requests did the job. I confirmed that the assets were created without IP, haven't noticed it before.

Thanks for the attention!

**Comment by WebGregGit** [comment]
Sorry, not everything is OK. I'm adding discovery quests again (I don't have any inventory quest yet).

The jobs end with error. But I can't see anything in php-errors or msql-errors.

"The agent requests a configuration that has already been sent to it by the server. It is likely that the agent is at risk of a fatal error"

From the plugin I see that job is still running. 
<html>
<body>


Started | 2022-07-04 15:20 |   | 3min 36s
-- | -- | -- | --



</body>
</html>
But from http://agent:port - I have a message that he is finished and waiting

**Comment by redddcyclone** [comment]
Actually I have another problem too. A network equipment is being detected by the network discovery as "Computer" instead of "Network equipment". As a result, import is denied. Is this related to these issues?

**Comment by stonebuzz** [comment]
> Actually I have another problem too. A network equipment is being detected by the network discovery as "Computer" instead of "Network equipment". As a result, import is denied. Is this related to these issues?

Be sur you have this fix -> https://github.com/glpi-project/glpi/pull/12050
Otherwise another issue would have to be created

**Comment by stonebuzz** [comment]
> Sorry @stonebuzz, not everything is OK. I'm adding discovery tasks again (I don't have any inventory task yet).
> 
> The jobs end with error. But I can't see anything in php-errors or msql-errors.
> 
> "The agent requests a configuration that has already been sent to it by the server. It is likely that the agent is at risk of a fatal error"
> 
> From the plugin I see that job is still running.
> Started 	2022-07-04 15:20 	  	8min 46s 	0 0 timeout
> 
> But from http://agent:port - I have a message that he is finished and waiting
> 
> [Mon Jul 4 15:20:35 2022][info] running task Inventory [Mon Jul 4 15:20:35 2022][info] New inventory from agent-2022-07-04-10-54-53 for server0 [Mon Jul 4 15:20:40 2022][info] [http client] SSL Client warning: Peer certificate not verified [Mon Jul 4 15:20:40 2022][info] [http client] SSL Client info: Cert-Issuer: '/C=PL/O=..... Validation CA SHA2', Cert-Subje> [Mon Jul 4 15:20:40 2022][info] [http client] SSL server certificate fingerprint: .... [Mon Jul 4 15:20:40 2022][info] [http client] You can set it in conf as 'ssl-fingerprint' and disable 'no-ssl-check' option to trust that server certificate [Mon Jul 4 15:20:40 2022][info] target server0: next run: Tue Jul 5 14:42:40 2022 - https://glpi.domain.com/front/inventory.php

Can you retry with GLPI-Agent 1.3 ?

**Comment by WebGregGit** [comment]
Just tried with agent 1.2 - same. The agent status - waiting. The task status - started

**Comment by stonebuzz** [comment]
> Just tried with agent 1.2 - same. The agent status - waiting. The task status - started
> 
> I tried again and from the agent's logs
> 
> [Mon Jul 4 15:49:19 2022] [info] target server0: server https://glpi.domain.com/front/inventory.php [Mon Jul 4 15:49:19 2022] [info] sending contact request to server0 **[Mon Jul 4 15:49:19 2022] [error] [http client] communication error: 400 Bad Request [Mon Jul 4 15:49:19 2022] [error] [http client] unexpected content, starting with: XML not well formed! [Mon Jul 4 15:49:19 2022] [error] No answer from server at https://glpi.domain.com/front/inventory.php** [Mon Jul 4 15:49:19 2022] [info] target server0: next run: Mon Jul 4 15:50:19 2022 - https://glpi.domain.com/front/inventory.php [Mon Jul 4 15:49:21 2022] [info] target local0: local / tmp [Mon Jul 4 15:49:21 2022] [info] running task RemoteInventory [Mon Jul 4 15:49:24 2022] [info] running task Inventory [Mon Jul 4 15:49:24 2022] [info] New inventory from agent-2022-04-30-23-45-40 for local0 [Mon Jul 4 15:49:26 2022] [info] Inventory saved in /tmp/agent-2022-04-30-23-45-40.xml [Mon Jul 4 15:49:26 2022] [info] target local0: next run: Mon Jul 4 16:42:33 2022 - / tmp

assuming you use the nightly build, you need to apply this -> https://github.com/glpi-project/glpi/pull/12127

**Comment by WebGregGit** [comment]
@stonebuzz yep - with this work like a charm.

Maybe it would be easier to wait for the nightly release and continue testing tomorrow?

Or I should try again with 1.4, but as I guess - with revert https://github.com/glpi-project/glpi/pull/12127  ?

**Comment by WebGregGit** [comment]
I don't remember what it looked like before. 

If that was the idea - OK. But it does not sum tasks, but displays the last one in the log. As a result, I still have 1 success - even if I am doing it again. This is with the agent 1.2. 

With the agent 1.4 and revert https://github.com/glpi-project/glpi/pull/12127 - problem exist
With the agent 1.3 and revert https://github.com/glpi-project/glpi/pull/12127 - the agent didn't even report to me on the server.

**Comment by stonebuzz** [comment]
> I don't remember what it looked like before.
> 
> If that was the idea - OK. But it does not sum tasks, but displays the last one in the log. As a result, I still have 1 success - even if I am doing it again. This is with the agent 1.2.

need another issue for this (does not sum tasks)

> With the agent 1.4 and revert [glpi-project/glpi#12127](https://github.com/glpi-project/glpi/pull/12127) - problem exist With the agent 1.3 and revert [glpi-project/glpi#12127](https://github.com/glpi-project/glpi/pull/12127) - the agent didn't even report to me on the server. I still see the 1.4-1 version (front/agent.php).


need another issue too (agent version not update)

**Comment by WebGregGit** [comment]
Hi @stonebuzz 

> need another issue for this (does not sum tasks)

https://github.com/glpi-project/glpi-inventory-plugin/issues/177

> need another issue too (agent version not update)

After install https://nightly.glpi-project.org/glpi/10.0-5cbba67.tar.gz version has been updated to 1.3.



What's left...
Still the agent finishes the job faster than the server.

But I think I will close this issue and open the new - will be more readable. https://github.com/glpi-project/glpi-inventory-plugin/issues/178
