### ISSUE TITLE
Huge CPU Load during SNMP inventory tasks

### ISSUE THREAD

**Issue by fabriceverkor** [glpi-project/glpi-inventory-plugin#302]
### Describe the bug

Huge CPU Load (>30) when an SNMP inventory task runs.  It make the GLPI Web interface unusable during 10 minutes

### To reproduce

Just let the task run.
the parameters are :
Threads number (network discovery) : 20
SNMP timeout (network discovery) : 1
Threads number (network inventory (snmp)) : 10
SNMP timeout (network inventory (snmp)) : 10

### Expected behavior

It should not have a impact on WEB interface

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.3

### GLPIInventory plugin

1.1.0

**Comment by cedric-anne** [comment]
> ### GLPI version
> 10.0.3

Even if it has probably no impact on this, you should upgrade to GLPI 10.0.6.

**Comment by g-bougard** [comment]
Hi @fabriceverkor 

is glpi-agent running on the same computer ?

As the agent is running it makes a lot of requests toward glpi server to log a lot of information with the task. You should probably check you server can support this load.
You may start by checking the httpd server supports enough  simultaneous requests. You can consider it should be able to answer 20 requests at the same time as you have 20 threads for the netdiscovery tasks.

Honestly, such problem is generally due to a misconfiguration with the httpd server. Did you find any error in php-errors.log or in glpi-agent log that could be a bug symptom ?
