### ISSUE TITLE
Office licences missing

### ISSUE THREAD

**Issue by lordimac** [glpi-project/glpi-inventory-plugin#304]
### Describe the bug

Office licences are missing in GLPI, but they are exported in json file from Agent.

Running latest GLPI 10.0.6, GLPI Native Inventory Plugin Version 1.1.0 from Marketplace and GLPI Agent 1.4 on Windows 11.

When I export/debug the agent output, I can see my licenses in the "licenseinfos" block (Replaced real part of Key with ABCDE and productid with numbers).

```
...
     "licenseinfos": [
         {
            "fullname": "Office 16, RETAIL channel",
            "key": "XXXXX-XXXXX-XXXXX-XXXXX-ABCDE",
            "name": "Office 16, Office16HomeBusinessR_Retail3 edition",
            "productid": "01234-56789-01234-56789"
         }
      ]
...
```

But I cant find this license in GLPI anywhere.

Im exporting directly to the GLPI Inventory Plugin with url domain.tld/marketplace/glpiinventory/

### To reproduce

Use GLPI Native Inventory and a json file with office licences.

### Expected behavior

Importing Office licences like with fustioninventory.

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.6

### GLPIInventory plugin

1.1.0

**Comment by trasher** [comment]
This is not a bug, but a missing "feature". When reintroducing fusioninventory features w'eve decided not to keep that part because we were really not happy with it.
Having a proper licenses management would be a quite huge job if we want a real generic solution. Feel free to open a request on GLPI (if no one exist yet) or contact pro support if you want to support development of this feature.
