### ISSUE TITLE
Not able to collect correct status of a win32_service ti

### ISSUE THREAD

**Issue by lexcyr** [glpi-project/glpi-inventory-plugin#322]
### Describe the bug

Hello,
When configuring the task to collect a win32_service status (e.g: "print spooler"), i am getting a wrong status (e.g: running instead of stopped) and a lot of tried in my logs:
![image](https://user-images.githubusercontent.com/10072663/222554874-62dfee08-cffa-4326-b06d-ada665984978.png)

Here is the tasks configuration:
![image](https://user-images.githubusercontent.com/10072663/222554678-87f3c9a1-7c9e-4797-80a7-b9e1678579b6.png)

here is the Task log (i have more than 100 lines like that:
![image](https://user-images.githubusercontent.com/10072663/222556185-238528d7-e6c4-4ff8-a907-1170ba3f97b5.png)

### To reproduce

1. Create a collect task for wmi
2. fill the WMi form
3. click in force start to prepare the task
4. run inventory from the server where the agent is installed

### Expected behavior

Get a result of "stopped" as the print spooler service is stopped on that server.
and not 210 retry on the log

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.6

### GLPIInventory plugin

1.1.0

**Comment by g-bougard** [comment]
Hi @lexcyr 

actually, you reached a GLPI-Agent limitation:
 - when requesting a WMI class, here the `Win32_Service`, it tries to report all the object, not the object for which you specified a name,
 - we don't support a WHERE clause with which you could select only one object.

As there's many objects in the `Win32_Service`, the agent pushes to the server the requested property for all the object. In your case, this means all service states are pushes one after one. And only the last one is associated to your collect information "Print Spooler"... and indeed even if it's "Running", you don't have any guarantee this is the state of print spooler service. If the last pushes state is "Stopped", even if your service is running, this is because this is the state of another service.

Indeed, the WMI collect information is only supporting for class which contains only one object.

The set name for the collected information is only a name to identify easily your information in the related GLPI asset tab. We can't use it as an object selector.

To enhance the feature, or we need to include a WHERE clause support on agent side, but this still means the plugin needs update, or the plugin could fully supports itself the WHERE clause or supports some output filtering.

As work-around, you can create a Deploy package to start a little script which just catch the expected value and put in a private registry key. Then you can use a Collect information to query the value you set in registry. You can force the tasks processing order using the `tasks` parameter of the agent. For example, you can set it to `deploy,inventory,collect,...`.
You can also run the script from a scheduled task.
