### ISSUE TITLE
Remove OCS - GLPI Inventory not works

### ISSUE THREAD

**Issue by pmrusek** [glpi-project/glpi-inventory-plugin#326]
### Describe the bug

We want to use GLPI Inventory. For this we uninstall OCS and installed GLPi Inventory-Plugin. The problem is that the agents not displayed as agents (Number of Agents is zero) and the computer is not active as Agent, so that i can do nothing. Also in Assets --> Computer the information is empty and the computer not synchronizing. When I use FusionInventory everything works with no problems. What can I do that GLPI-Inventory also works like FusionInventory. When i use an empty glpi installation GLPI-Inventory works. But when before OCS is installed than it is not working.

### To reproduce

Just install OCS import Computer
Than uninstall OCS and install GLPI-Inventory.

### Expected behavior

No computer synced, no task i can assign to agents.

### Operating system

Linux

### GLPI Agent version

1.4

### GLPI version

10.0.6

### GLPIInventory plugin

1.1.0

**Comment by trasher** [comment]
There is no link between OCS inventory and fusioninventory. I do not know how OCS works, neither if it creates agents, but if it does, it's in their own tables.
Agents are created on computer inventory; nothing is migrated from OCS.

Note that glpiinventory plugin is designed for SNMP discovery and inventory only GLPI itself is enough to inventory computers. And if there is an error; you'll find details in the logs and have to provide it whe you report an issue.

I close since this seems rather a support question than a bug.
