### ISSUE TITLE
GLPI market error after installing GLPI Inventory Uncaught Exception ParseError: syntax error, unexpected character 0x00, expecting end of file in /var/www/html/comit/marketplace/glpiinventory/setup.php

### ISSUE THREAD

**Issue by IkhsanLPK** [glpi-project/glpi-inventory-plugin#329]
ParseError: syntax error, unexpected character 0x00, expecting end of file in /var/www/html/glpi/marketplace/glpiinventory/setup.php

**Comment by IkhsanLPK** [comment]
[setup.zip](https://github.com/glpi-project/glpi-inventory-plugin/files/10999930/setup.zip)

**Comment by cedric-anne** [comment]
Hi,

What is your PHP version?

**Comment by IkhsanLPK** [comment]
Hi @cedric-anne,

i use this version

PHP 8.2.3 (cli) (built: Feb 14 2023 01:06:39) (NTS gcc x86_64)
Copyright (c) The PHP Group
Zend Engine v4.2.3, Copyright (c) Zend Technologies

**Comment by cedric-anne** [comment]
A similar issues has been reported in #254 (was on PHP 8.2 RC version), so I guess it is due to an issue in PHP 8.2, but I was not able to reproduce on PHP 8.2.4. Could you try to update your PHP version, remove the `marketplace/glpiinventory` directory, and try again?

If problem persist, solution is to extract the release archive manually.

**Comment by IkhsanLPK** [comment]
@cedric-anne ,

Great! glpiinventory work after updating PHP version to 

_PHP 8.2.4 (cli) (built: Mar 14 2023 16:11:05) (NTS gcc x86_64)
Copyright (c) The PHP Group
Zend Engine v4.2.4, Copyright (c) Zend Technologies_

Thanks! Closed!
