### ISSUE TITLE
NET INVENTORY SNMP : Many timeout

### ISSUE THREAD

**Issue by waaalex** [glpi-project/glpi-inventory-plugin#455]
### Describe the bug

Hello,
We have a lot of inventory jobs.
And many timeout.
You will see in attachment examples of error in net inventory status.
Regards.
Alex.

### To reproduce

Every days, i can see timeout in job reports.

### Expected behavior

No timeout.
![TimeOutGLPI](https://github.com/glpi-project/glpi-inventory-plugin/assets/33757865/aef0bd94-6150-42d4-b41d-716e45ed0822)

### Operating system

Linux

### GLPI Agent version

1.6.1

### GLPI version

10.0.10

### GLPIInventory plugin

1.3.3

**Comment by stonebuzz** [comment]
This column displays only the agent configuration (GLPI side)  send to Agent

![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/7335054/da577ac8-86a9-4322-8bbf-ccff3b132e7d)

1 (for thread) / 15 sec for timeout

![image](https://github.com/glpi-project/glpi-inventory-plugin/assets/7335054/fa878daf-933c-40a3-848b-0a9cd58f3e2a)

This PR https://github.com/glpi-project/glpi-inventory-plugin/pull/457

add more precise label and all info 

```1 threads 15 timeout``` instead of ```1 15 timeout```

**Comment by waaalex** [comment]
Wonderfull.
I mean that it will be corrected on futur release.
![erreur maj](https://github.com/glpi-project/glpi-inventory-plugin/assets/33757865/bc777b13-7123-42ea-ac0e-5ab0ae861782)

Thanks.
I close this issue.
